spring:
  h2:
    console:
      enabled: true
  jpa:
    properties:
      show_sql: true
      format_sql: true
      use_sql_comments: true
  mustache:
    suffix: .html
logging:
  level:
    root: debug
